### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by akscoder082003** [OnCampus-Community/Udemy-Course-EDA#2]
![Screenshot 2023-09-27 092341](https://github.com/OnCampus-Community/Udemy-Course-EDA/assets/109755100/79fe11c5-ce86-4437-b231-5307f6a8b608)

Check this out !

**Comment by IishuJainn** [comment]
@akscoder082003 You might've have run the cells in an improper sequence, run them in proper sequence again and if you want you can replace this line of code with 
ax = sns.countplot(x='level',data=df, palette = ["maroon", "darkblue"])

**Comment by akscoder082003** [comment]
@IishuJainn okay i will try this out and update it.

**Comment by akscoder082003** [comment]
> @akscoder082003 You might've run the cells in an improper sequence, run them in proper sequence again and if you want you can replace this line of code with ax = sns.countplot(x='level',data=df, palette = ["maroon", "darkblue"])

yep this code of line solved the issue,
could i update in the main.
