### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by akscoder082003** [OnCampus-Community/Udemy-Course-EDA#3]
![Screenshot 2023-09-27 092401](https://github.com/OnCampus-Community/Udemy-Course-EDA/assets/109755100/8a55c0f3-9a52-45b0-af66-3fb264a5d018)

Check this out !!

**Comment by deepraj02** [comment]
Can u fix it ?

**Comment by akscoder082003** [comment]
> Can u fix it ?
> 

Mene try Kiya, but hua nhi.

**Comment by IishuJainn** [comment]
@akscoder082003 You can use :
sns.kdeplot(df['course_duration'], shade = True);

**Comment by akscoder082003** [comment]
> @akscoder082003 You can use : sns.kdeplot(df['course_duration'], shade = True);

yep this solved the issue,

**Comment by akscoder082003** [comment]
@IishuJainn  Could i update the code.

**Comment by akscoder082003** [comment]
> @IishuJainn Could i update the code.

@deepraj02 update karu kya

**Comment by deepraj02** [comment]
Yupp kr do update @akscoder082003
